# Funcion de Calculo de Primas ............................................
calculo_producto = function(producto,Edad,Sexo,Tipo_interes,Duracion,Cuantia,
                            Tipo_crecimiento,Crecimiento,Gastos_internos,
                            Gastos_externos, Numero_primas,Temporalidad,...){
  require(lifecontingencies)
  respuesta = 
    switch (producto,
            #...............................#...............................
            # Seguros de Vida  .............#...............................
            #...............................#...............................
            '1_fallecimiento' = {
              l = list()
              tabla = switch(Sexo,'Hombre' = {TH},'Mujer' = {TM})
              #...............................
              l$prima_pura = Axn(tabla , x = Edad, n = Cobertura, i = Tipo_interes, k = 1)
              l$prima_pura = l$prima_pura*Cuantia
              #...............................
              l$prima_inventario = Axn(tabla , x = Edad, n = Cobertura, i = Tipo_interes, k = 1)*(1+Gastos_internos)
              l$prima_inventario = l$prima_inventario*Cuantia
              #...............................
              l$prima_comercial = Axn(tabla , x = Edad, n = Cobertura, i = Tipo_interes, k = 1)*(1+Gastos_internos)*(1+Gastos_externos)
              l$prima_comercial = l$prima_comercial*Cuantia
              #...............................
              if(Seleccion_frac == 'Si'){
                l$prima_fraccionada = (Axn(tabla , x = Edad, n = Cobertura, i = Tipo_interes, k = 1)/
                                         axn(tabla, x = Edad, n = Fraccion, i = Tipo_interes, k = Temporalidad, payment = 'due'))/Temporalidad
                l$prima_fraccionada = l$prima_fraccionada * Cuantia
              }else{
                l$prima_fraccionada = "No se calculó"
              }
              #...............................
              l$reserva = c()
              P = l$prima_pura
              PNivel = P/axn(tabla, x= Edad, n = Cobertura, i = Tipo_interes, m = 0, k = 1, payment = "due")
              Reserva = function(t){
                return(Cuantia*Axn(tabla, x=Edad+t, n=Cobertura-t, i=Tipo_interes, m=0, k=1) - 
                         PNivel*axn(tabla, x=Edad+t, n=Cobertura-t, i=Tipo_interes, m=0, payment = "immediate", k=1))
              } 
              for(t in 0:15){l$reserva[t] = Reserva(t)}
              #...............................
              l
            },
            #...............................
            #...............................
            #...............................
            '1_supervivencia' = {
              l = list()
              tabla = switch(Sexo,'Hombre' = {TH},'Mujer' = {TM})
              #...............................
              l$prima_pura = Exn(tabla , x = Edad, n = Cobertura, i = Tipo_interes)
              l$prima_pura = l$prima_pura*Cuantia
              #...............................
              l$prima_inventario = Exn(tabla , x = Edad, n = Cobertura, i = Tipo_interes)*(1+Gastos_internos)
              l$prima_inventario = l$prima_inventario*Cuantia
              #...............................
              l$prima_comercial = Exn(tabla , x = Edad, n = Cobertura, i = Tipo_interes)*(1+Gastos_internos)*(1+Gastos_externos)
              l$prima_comercial = l$prima_comercial*Cuantia
              #...............................
              if(Seleccion_frac == 'Si'){
                l$prima_fraccionada = (Exn(tabla , x = Edad, n = Cobertura, i = Tipo_interes)/
                                         axn(tabla, x = Edad, n = Fraccion, i = Tipo_interes, k = Temporalidad, payment = 'due'))/Temporalidad
                l$prima_fraccionada = l$prima_fraccionada * Cuantia
              }else{
                l$prima_fraccionada = "No se calculó"
              }
              #...............................
              l$reserva = c()
              P = l$prima_pura
              PNivel = P/axn(tabla, x= Edad, n = Cobertura, i = Tipo_interes, m = 0, k = Temporalidad, payment = "due")
              Reserva = function(t){
                return(Cuantia*Exn(tabla, x=Edad+t, n=Cobertura-t, i=Tipo_interes, m=0) - 
                         PNivel*axn(tabla, x=Edad+t, n=Cobertura-t, i=Tipo_interes, m=0, payment = "immediate", k=Temporalidad))
              } 
              for(t in 0:15){l$reserva[t] = Reserva(t)}
              #...............................
              l
            },
            #...............................
            #...............................
            #...............................
            '1_mixto' = {
              l = list()
              tabla = switch(Sexo,'Hombre' = {TH},'Mujer' = {TM})
              #...............................
              l$prima_pura = ""
              #...............................
              l$prima_inventario = ""
              #...............................
              l$prima_comercial = ""
              #...............................
              l$prima_fraccionada = ""
              #...............................
              l$reserva = ""
              #...............................
              l
            },
            
            #...............................#...............................
            # Rentas   .....................#...............................
            #...............................#...............................
            '2_prepagables' = {
              l = list()
              tabla = switch(Sexo,'Hombre' = {TH},'Mujer' = {TM})
              #...............................
              l$prima_pura = ""
              #...............................
              l$prima_inventario = ""
              #...............................
              l$prima_comercial = ""
              #...............................
              l$prima_fraccionada = ""
              #...............................
              l$reserva = ""
              #...............................
              l
            },
            #...............................
            #...............................
            #...............................
            '2_pospagables' = {
              l = list()
              tabla = switch(Sexo,'Hombre' = {TH},'Mujer' = {TM})
              #...............................
              l$prima_pura = ""
              #...............................
              l$prima_inventario = ""
              #...............................
              l$prima_comercial = ""
              #...............................
              l$prima_fraccionada = ""
              #...............................
              l$reserva = ""
              #...............................
              l
            }
    )
  
  return(respuesta)
}